#!/bin/bash

alias g="git"
alias j="jump"

# Shopify
alias test="bin/test --include-branch-commits"
alias style="bin/style --include-branch-commits"
alias check="bin/style --include-branch-commits;bin/srb typecheck -a"
alias logs="tail -f log/development.log"
