#!/bin/bash

alias g="git"
alias lj="longjump"

# Shopify
alias ljs="longjump spin"
alias check="bin/style --include-branch-commits;bin/srb typecheck -a"
alias logs="tail -f log/development.log"
alias hermit="rake tests:hermeticize"
alias up="bundle install;bin/rails db:migrate"

function style() {
    if [ -f "bin/style" ]; then
        bin/style --include-branch-commits
    else
        yarn run eslint --fix $(git diff --name-only main | xargs)
    fi
}

function tests() {
    if [ -f "bin/test" ]; then
        bin/test --include-branch-commits
    else
        yarn test --changedSince main
    fi
}
